require('dotenv').config();
const DATABASE_USER = process.env.DATABASE_USER,
// console.log(process.env.DATABASE_USER);
DATABASE_HOST =process.env.DATABASE_HOST,
DATABASE_NAME = process.env.DATABASE_NAME,
DATABASE_PASSWORD=  process.env.DATABASE_PASSWORD,
DATABASE_PORT= process.env.DATABASE_PORT,
JWT_SECRET = process.env.JWT_SECRET
module.exports = {
 DATABASE_USER,
 DATABASE_HOST,
 DATABASE_NAME,
 DATABASE_PASSWORD,
 DATABASE_PORT,
 JWT_SECRET
}
